name: Node.js Jest Tests and Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
  SECRET: ${{ secrets.SECRET }}
  PORT: ${{ secrets.PORT }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run tests and check coverage
        run: |
          coverage=$(npx jest --showConfig \
            | grep coverageThreshold \
            | awk '{print $3}' \
            | tr -d ',' \
            | sed 's/"//g')
          threshold=50
          if (( $(echo "$coverage < $threshold" | bc -l) )); then
            echo "Test coverage is less than $threshold%. Aborting merge."
            exit 1
          fi


